import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react'

export default function Home() {
  const [balances, setBalances] = useState(null)
  
  useEffect(() => {
    const fetchBalances = async () => {
      const response = await fetch('/api/solana', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
      });

      // if (!response.ok) {
      //   throw new Error(`Error: ${response.status}`);
      // }

      const resp = await response.json();
      setBalances(resp.value)
    }

    fetchBalances();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>🌼 SOLANA 🌼</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {balances ?
            balances.map((balance, idx) => (
              <div key={idx}>{balance.lamports}</div>
            )) : ''}
        </div>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}
